#!/usr/bin/perl -w
use strict;
use Socket;

socket(Client,PF_UNIX,SOCK_STREAM,0);
connect(Client,sockaddr_un("/tmp/zimwm-ipc"))
		or die "$!";

select((select(Client), $| = 1)[0]);

print Client "help me";

recv(Client,my $response, 5, 0);

print "$response\n";

close(Client);
0;
