#!/usr/bin/perl -w
use strict;
use Socket;

while(1) {
	print "zimwm> ";
	my $input = <>;

	chop $input;
	
	if($input eq "exit" or $input eq "quit") {
		last;
	}

	socket(Client,PF_UNIX,SOCK_STREAM,0);
	connect(Client,sockaddr_un("/tmp/zimwm-ipc"))
			or die "$!";
	
	select((select(Client), $| = 1)[0]);	
	
	print Client $input;

	recv(Client,my $response, 500, 0);

	print "$response\n";
	close(Client);
}

close(Client);

0;
